#!/bin/bash

### a simple script to call other executables and draw samples from the requested distributions
### Reed Essick (reed.essick@gmail.com)

#--------------------------------------------

NUM_SAMPLES=10000                    ### the number of samples to draw from each distribution
NETWORKS="ce hlv"                    ### the detector networks to consider
POPULATIONS="astrophysical detected" ### the populations to consider for each network

#--------------------------------------------

# iterate through detector newtorks
for network in $NETWORKS
do
    # draw samples for both astrophysical and detected populations
    for pop in $POPULATIONS
    do

        mcvt-sample \
            "${network}-${pop}-population.ini" \
            $NUM_SAMPLES \
            --seed 1234 \
            --output-path "${network}-${pop}-population.hdf5" \
            --Verbose

    done
done
